In [ ]:
!pip install sklearn
from sklearn.impute import  SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures,MinMaxScaler

# pipline
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import FunctionTransformer

#classification model
from sklearn.neighbors import KNeighborsClassifier

#grid search
from sklearn.model_selection import GridSearchCV, train_test_split

# optional: pipeline visualization
from sklearn import set_config
set_config(display='diagram')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sklearn
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2344 sha256=8a54fea6f48402ee06b2e7136eee92b6268dfd6c28b28e0b7301f5b34c98a6a7
  Stored in directory: /root/.cache/pip/wheels/14/25/f7/1cc0956978ae479e75140219088deb7a36f60459df242b1a72
Successfully built sklearn
Installing collected packages: sklearn
Successfully installed sklearn-0.0.post1

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
tqdm.pandas()

In [ ]:
!pip install tensorflow
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tensorflow in /usr/local/lib/python3.8/dist-packages (2.9.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (0.29.0)
Requirement already satisfied: flatbuffers<2,>=1.12 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.12)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.1.2)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (4.4.0)
Requirement already satisfied: tensorboard<2.10,>=2.9 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (2.9.1)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.51.1)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.15.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.3.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from tensorflow) (57.4.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (2.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (14.0.6)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (2.9.0)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (1.21.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from tensorflow) (21.3)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (3.19.6)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow) (2.2.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.8/dist-packages (from astunparse>=1.6.0->tensorflow) (0.38.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow) (3.4.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow) (0.4.6)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.25.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.15.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow) (1.8.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow) (0.6.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->tensorflow) (3.0.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (5.2.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (6.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (4.0.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (3.11.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow) (3.2.2)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xgboost in /usr/local/lib/python3.8/dist-packages (0.90)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from xgboost) (1.7.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from xgboost) (1.21.6)

# Begining of the project

In [ ]:
reg_season=pd.read_csv('https://raw.githubusercontent.com/sebastiancoombs/Kaggle_2022_MM/main/mens-march-mania-2022/MDataFiles_Stage1/MRegularSeasonDetailedResults.csv')

In [ ]:
conf = pd.read_csv('https://raw.githubusercontent.com/sebastiancoombs/Kaggle_2022_MM/main/mens-march-mania-2022/MDataFiles_Stage1/MTeamConferences.csv')
conf['TeamID']=conf.Season.astype(str)+'_'+conf.TeamID.astype(str)
conf

       Season     TeamID ConfAbbrev
0        1985  1985_1102        wac
1        1985  1985_1103        ovc
2        1985  1985_1104        sec
3        1985  1985_1106       swac
4        1985  1985_1108       swac
...       ...        ...        ...
12294    2022  2022_1468      a_sun
12295    2022  2022_1469        wac
12296    2022  2022_1470        wac
12297    2022  2022_1471   big_west
12298    2022  2022_1472     summit

[12299 rows x 3 columns]

In [ ]:
reg_season

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100418,2022,98,1400,79,1242,76,H,0,28,67,...,13,15,23,5,24,10,15,3,5,21
100419,2022,98,1411,66,1126,63,A,0,24,59,...,21,15,24,5,23,10,19,13,2,23
100420,2022,98,1422,68,1441,49,A,0,23,56,...,24,8,11,10,18,5,16,8,2,12
100421,2022,98,1438,69,1181,68,A,0,31,65,...,17,18,22,11,25,14,14,3,9,11
100422,2022,98,1439,74,1338,47,H,0,29,55,...,20,7,9,0,18,11,11,3,6,14

In [ ]:
season_ranks=pd.read_csv('https://raw.githubusercontent.com/sebastiancoombs/Kaggle_2022_MM/main/mens-march-mania-2022/MDataFiles_Stage1/MMasseyOrdinals.csv')

In [ ]:
data=reg_season[(reg_season.Season==2021) &(reg_season.WTeamID==1468)]
data=data.sort_values('DayNum')
year=data.Season.unique()[0]
team=data.LTeamID.unique()[0]
team_data=data
team_data.tail(5)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
95122,2021,89,1468,84,1244,79,A,0,29,48,...,26,13,15,7,20,12,15,6,1,0
95287,2021,95,1468,71,1239,56,H,0,30,61,...,22,5,8,7,22,8,18,5,5,0
95385,2021,96,1468,63,1239,44,H,0,25,55,...,22,9,16,9,19,6,12,5,2,0
95552,2021,102,1468,66,1466,64,A,0,22,48,...,28,9,12,8,19,13,17,4,2,0
95658,2021,103,1468,87,1466,63,A,0,34,61,...,28,10,10,9,17,13,27,1,3,0

In [ ]:
ranks=season_ranks.pivot_table(index=['Season','TeamID','RankingDayNum'],values='OrdinalRank',columns='SystemName')
ranks=ranks.groupby(level=[0,1]).fillna(method='ffill')
ranks=ranks.fillna(0)
ranks=ranks.reset_index()
ranks.columns.name=''
ranks.head(5)
trash_rankings=[]
size=len(ranks)
for col in ranks:
  ## if most of the data in the ranking column is nothing drop it
  if ranks[col].replace(0,np.nan).isna().sum() >size/4: 
    trash_rankings.append(col)
    ranks=ranks.drop(col,axis=1)
print('dropped these trash rankings',trash_rankings)

dropped these trash rankings ['7OT', 'ACU', 'ADE', 'AP', 'ARG', 'ATP', 'AUS', 'AWS', 'BAR', 'BBT', 'BCM', 'BD', 'BIH', 'BKM', 'BLS', 'BNM', 'BNT', 'BNZ', 'BOB', 'BOW', 'BP5', 'BPI', 'BRZ', 'BUR', 'BWE', 'CBR', 'CJB', 'CMV', 'CNG', 'COL', 'COX', 'CPA', 'CPR', 'CRO', 'CRW', 'CTL', 'CWL', 'D1A', 'DAV', 'DC', 'DC2', 'DCI', 'DDB', 'DES', 'DII', 'DP', 'DUN', 'DWH', 'EBB', 'EBP', 'ECK', 'EMK', 'ENT', 'ERD', 'ESR', 'FAS', 'FDM', 'FMG', 'FSH', 'GC', 'GRN', 'GRS', 'HAS', 'HAT', 'HER', 'HKB', 'HKS', 'HOL', 'HRN', 'IMS', 'INC', 'INP', 'ISR', 'JCI', 'JEN', 'JJK', 'JNG', 'JON', 'JRT', 'KBM', 'KCX', 'KEL', 'KLK', 'KMV', 'KOS', 'KPI', 'KPK', 'KRA', 'LAB', 'LAW', 'LEF', 'LMC', 'LOG', 'LYD', 'LYN', 'MAS', 'MB', 'MCL', 'MGS', 'MGY', 'MIC', 'MKV', 'MMG', 'MPI', 'MSX', 'MUZ', 'MvG', 'NET', 'NOL', 'NOR', 'OCT', 'OMN', 'OMY', 'PEQ', 'PGH', 'PH', 'PIG', 'PIR', 'PKL', 'PMC', 'PPR', 'PRR', 'PTS', 'RAG', 'REI', 'REN', 'REW', 'RIS', 'RM', 'ROG', 'ROH', 'RPI', 'RSE', 'RSL', 'RT', 'RTB', 'RTH', 'RTP', 'RTR', 'RWP', 'SAP', 'SAU', 'SCR', 'SE', 'SEL', 'SFX', 'SGR', 'SIM', 'SMN', 'SMS', 'SP', 'SPR', 'SPW', 'SRS', 'STF', 'STH', 'STM', 'STR', 'STS', 'TBD', 'TMR', 'TOL', 'TPR', 'TRK', 'TRP', 'TRX', 'TS', 'TSR', 'TW', 'UCS', 'UPS', 'USA', 'WIL', 'WLS', 'WMR', 'WMV', 'WOB', 'WOL', 'WTE', 'YAG', 'ZAM']

In [ ]:
def getclosest(n,ranking_days):
  before=[0]
  before=before+[r for r in ranking_days if r<n]
  return np.max(before)

In [ ]:
def getclosest_Wrankingday(data):
    year=data['Season'].unique()[0]
    team=data['WTeamID'].unique()[0]
    team_ranks=ranks.loc[(ranks.Season==year) &(ranks.TeamID==team),'RankingDayNum']
    ranking_days=team_ranks.values
    game_days=data.DayNum.values
    closest_rankings=[getclosest(r,ranking_days) for r in game_days]
    data['WRank_day']=closest_rankings
    return data

def getclosest_Lrankingday(data):
    year=data['Season'].unique()[0]
    team=data['LTeamID'].unique()[0]
    team_ranks=ranks.loc[(ranks.Season==year) &(ranks.TeamID==team),'RankingDayNum']
    ranking_days=team_ranks.values
    game_days=data.DayNum.values
    closest_rankings=[getclosest(r,ranking_days) for r in game_days]
    data['LRank_day']=closest_rankings
    return data

In [ ]:
reg_season=reg_season.groupby(['Season','WTeamID']).progress_apply(getclosest_Wrankingday)
reg_season=reg_season.groupby(['Season','LTeamID']).progress_apply(getclosest_Lrankingday)
reg_season['WTeamID']=reg_season.Season.astype(str)+'_'+reg_season.WTeamID.astype(str)
reg_season['LTeamID']=reg_season.Season.astype(str)+'_'+reg_season.LTeamID.astype(str)
reg_season.head(3)
reg_season.Season.unique()

  0%|          | 0/6883 [00:00<?, ?it/s]

  0%|          | 0/6889 [00:00<?, ?it/s]

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [ ]:

ranks['TeamID']=ranks.Season.astype(str)+'_'+ranks.TeamID.astype(str)
ranks.head(3)

   Season     TeamID  RankingDayNum  DOK  DOL    MOR    POM    SAG    WLK
0    2003  2003_1102             35  0.0  0.0    0.0    0.0    0.0    0.0
1    2003  2003_1102             37  0.0  0.0  110.0  104.0  114.0  103.0
2    2003  2003_1102             42  0.0  0.0  110.0  104.0  114.0  103.0

In [ ]:
w_games=reg_season.filter(regex='^W',).copy()
w_games=pd.concat([reg_season[['Season','DayNum']],w_games],axis=1)
w_games.columns=[w.replace('W','',1) for w in w_games.columns]

l_games=reg_season.filter(regex='^L',).copy()
l_games=pd.concat([reg_season[['Season','DayNum']],l_games],axis=1)
l_games.columns=[l.replace('L','',1) for l in l_games.columns]

In [ ]:
w_games

,Season,DayNum,TeamID,Score,Loc,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF,Rank_day
0,2003,10,2003_1104,68,N,27,58,3,14,11,18,14,24,13,23,7,1,22,0
1,2003,10,2003_1272,70,N,26,62,8,20,10,19,15,28,16,13,4,4,18,0
2,2003,11,2003_1266,73,N,24,58,8,18,17,29,17,26,15,10,5,2,25,0
3,2003,11,2003_1296,56,N,18,38,3,9,17,31,6,19,11,12,14,2,18,0
4,2003,11,2003_1400,77,N,30,61,6,14,11,13,17,22,12,14,4,4,20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100418,2022,98,2022_1400,79,H,28,67,3,20,20,23,14,18,8,6,7,2,21,93
100419,2022,98,2022_1411,66,A,24,59,2,20,16,28,12,27,9,19,10,5,19,93
100420,2022,98,2022_1422,68,A,23,56,13,32,9,13,11,22,11,15,11,1,13,93
100421,2022,98,2022_1438,69,A,31,65,2,12,5,9,10,20,16,5,10,2,17,93
100422,2022,98,2022_1439,74,H,29,55,13,27,3,6,9,26,20,8,6,1,12,93

In [ ]:
w_games_ranked=pd.merge(w_games,ranks.drop('Season',axis=1),left_on=['TeamID','Rank_day'],right_on=['TeamID','RankingDayNum'])
l_games_ranked=pd.merge(l_games,ranks.drop('Season',axis=1),left_on=['TeamID','Rank_day'],right_on=['TeamID','RankingDayNum'])

In [ ]:

#create season of games
games=pd.concat([w_games,l_games],axis=0)
games_ranked=pd.concat([w_games_ranked,l_games_ranked],axis=0)

games=games.sort_values(['TeamID','Rank_day'])
games_ranked=games_ranked.sort_values(['TeamID','Rank_day'])

In [ ]:
games=pd.merge(games,conf.drop('Season',axis=1),left_on='TeamID',right_on='TeamID',how='left')
games=games.set_index('TeamID')
games_ranked=pd.merge(games_ranked,conf.drop('Season',axis=1),left_on='TeamID',right_on='TeamID',how='left')
games_ranked=games_ranked.set_index('TeamID')

In [ ]:
games.tail(3)

,TeamID,Season,DayNum,Score,Loc,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF,Rank_day,ConfAbbrev
200843,2022_1472,2022,89,52,NaN,18,56,7,32,9,12,4,19,10,11,6,0,16,86,summit
200844,2022_1472,2022,94,72,NaN,26,51,3,12,17,19,3,20,6,13,4,3,18,93,summit
200845,2022_1472,2022,96,66,NaN,27,66,6,25,6,9,8,20,8,6,4,1,13,93,summit

In [ ]:
games_ranked.head(3)

,Season,DayNum,Score,Loc,FGM,FGA,FGM3,FGA3,FTM,FTA,...,PF,Rank_day,RankingDayNum,DOK,DOL,MOR,POM,SAG,WLK,ConfAbbrev
TeamID,,,,,,,,,,,,,,,,,,,,,
2003_1102,2003,37,85,H,26,41,12,23,21,32,...,19,35,35,0.0,0.0,0.0,0.0,0.0,0.0,mwc
2003_1102,2003,48,44,NaN,16,45,8,27,4,7,...,25,44,44,0.0,0.0,106.0,84.0,78.0,52.0,mwc
2003_1102,2003,54,63,A,21,44,11,26,10,18,...,20,51,51,0.0,0.0,127.0,126.0,113.0,52.0,mwc

In [ ]:
games.to_csv('Games_by_team.csv')
games_ranked.to_csv('Games_with_rankings_by_team.csv')

In [ ]:
baseline=games.groupby(['ConfAbbrev','Season']).mean()
games=games.reset_index()
baseline_ranked=games_ranked.groupby(['ConfAbbrev','Season']).mean()
games_ranked=games_ranked.reset_index()
baseline.head(2)

                      DayNum      Score        FGM        FGA      FGM3  \
ConfAbbrev Season
a_sun      2003    71.815476  71.065476  25.383929  58.145833  7.077381
           2004    74.812081  71.664430  25.500000  58.959732  7.456376

                        FGA3        FTM        FTA         OR         DR  \
ConfAbbrev Season
a_sun      2003    20.619048  13.220238  18.889881  11.991071  22.958333
           2004    21.755034  13.208054  19.127517  12.583893  23.164430

                         Ast         TO       Stl       Blk         PF  \
ConfAbbrev Season
a_sun      2003    14.375000  15.642857  7.910714  3.318452  18.372024
           2004    14.442953  15.463087  8.033557  3.325503  18.516779

                    Rank_day
ConfAbbrev Season
a_sun      2003    65.854167
           2004    72.265101

In [ ]:
baseline_ranked.head(2)

                      DayNum      Score        FGM        FGA      FGM3  \
ConfAbbrev Season
a_sun      2003    81.748201  71.766187  25.715827  58.266187  7.136691
           2004    75.233108  71.726351  25.527027  58.989865  7.459459

                        FGA3        FTM        FTA         OR         DR  ...  \
ConfAbbrev Season                                                         ...
a_sun      2003    20.737410  13.197842  18.762590  12.151079  22.982014  ...
           2004    21.777027  13.212838  19.131757  12.587838  23.141892  ...

                        Blk         PF   Rank_day  RankingDayNum  DOK  \
ConfAbbrev Season
a_sun      2003    3.323741  18.237410  79.593525      79.593525  0.0
           2004    3.310811  18.503378  72.753378      72.753378  0.0

                          DOL         MOR         POM         SAG         WLK
ConfAbbrev Season
a_sun      2003     73.266187  226.820144  210.442446  209.302158  199.334532
           2004    162.935811  172.476351  210.625000  203.695946  171.043919

[2 rows x 23 columns]

In [ ]:
games_ranked.tail(3)

,TeamID,Season,DayNum,Score,Loc,FGM,FGA,FGM3,FGA3,FTM,...,PF,Rank_day,RankingDayNum,DOK,DOL,MOR,POM,SAG,WLK,ConfAbbrev
189985,2022_1472,2022,89,52,NaN,18,56,7,32,9,...,16,86,86,283.0,278.0,282.0,267.0,322.0,253.0,summit
189986,2022_1472,2022,94,72,NaN,26,51,3,12,17,...,18,93,93,292.0,289.0,310.0,277.0,332.0,276.0,summit
189987,2022_1472,2022,96,66,NaN,27,66,6,25,6,...,13,93,93,292.0,289.0,310.0,277.0,332.0,276.0,summit

In [ ]:
#pick out the team, season and conference and drop the rankings
team=games[games['TeamID']=='2022_1383']
season=int(team['TeamID'].unique()[0].split('_')[0])
teamid=team['TeamID'].unique()[0]
con=team.ConfAbbrev.unique()[0]
team=team.drop('ConfAbbrev',axis=1)
conf_avg=baseline.loc[con,season]
#sumtract and sum for plus minus
pm=team-conf_avg
pm=pm.sum(axis=0)
pm.loc['TeamID']=teamid
pm

Ast         -7.780952
Blk         -18.87619
DR          -24.07619
DayNum       4.495238
FGA         46.847619
FGA3        21.161905
FGM         -0.685714
FGM3        -0.485714
FTA        -33.866667
FTM        -19.761905
Loc                 0
OR          13.628571
PF           0.180952
Rank_day    12.295238
Score      -21.619048
Season            0.0
Stl         -4.342857
TO         -25.552381
TeamID      2022_1383
dtype: object

In [ ]:
#pick out the team, season and conference and normalize including the rankings
team=games_ranked[games_ranked['TeamID']=='2022_1383']
season=int(team['TeamID'].unique()[0].split('_')[0])
teamid=team['TeamID'].unique()[0]
con=team.ConfAbbrev.unique()[0]
team=team.drop(['ConfAbbrev','TeamID'],axis=1)
conf_avg.filter(like='a')
#subtract divide by averages
norm=(team-conf_avg)/conf_avg
norm=norm.fillna(0)
norm.head(5)

,Ast,Blk,DOK,DOL,DR,DayNum,FGA,FGA3,FGM,FGM3,...,PF,POM,Rank_day,RankingDayNum,SAG,Score,Season,Stl,TO,WLK
188364,-0.125662,-0.370315,0.0,0.0,-0.281744,-0.683455,0.041802,0.021446,0.021004,0.016598,...,0.196240,0.0,-0.675488,0.0,0.0,-0.120965,0.0,0.334746,-0.215833,0.0
188365,0.033308,-0.685157,0.0,0.0,-0.057289,-0.590353,0.024723,0.207163,-0.019837,0.597510,...,0.136428,0.0,-0.675488,0.0,0.0,0.042923,0.0,0.483051,0.489918,0.0
188366,-0.205148,-0.370315,0.0,0.0,-0.102180,-0.534492,-0.163142,-0.117842,-0.183197,-0.564315,...,0.016804,0.0,-0.533514,0.0,0.0,-0.120965,0.0,-0.406780,0.254668,0.0
188367,0.192279,-0.370315,0.0,0.0,-0.012398,-0.515872,-0.077749,-0.117842,0.021004,-0.273859,...,-0.162632,0.0,-0.533514,0.0,0.0,-0.001774,0.0,-0.258475,0.254668,0.0
188368,-0.443603,-0.055472,0.0,0.0,0.167165,-0.441390,0.075960,-0.210701,-0.305718,-0.419087,...,0.315864,0.0,-0.533514,0.0,0.0,-0.314651,0.0,0.334746,0.097834,0.0

In [ ]:
def normalize_by_conf(data):
    team=data
    season=int(team['TeamID'].unique()[0].split('_')[0])
    teamid=team['TeamID'].unique()[0]
    con=team.ConfAbbrev.unique()[0]
    team=team.drop('ConfAbbrev',axis=1)
    # team=team.drop('TeamID',axis=1)
    conf_avg=baseline.loc[con,season]
    #subtract and sume for plus minus
    norm=(team-conf_avg)/conf_avg
    norm['TeamID']=teamid
    norm=norm.fillna(0)
    return norm

In [ ]:
#ignore ranking columns
def plus_minus(data):
    #pick out the team, season and conference and drop the rankings
    team=data.copy()
    teamid=team['TeamID'].unique()[0]
    season=int(team['TeamID'].unique()[0].split('_')[0])
    con=team.ConfAbbrev.unique()[0]
    team=team.drop('ConfAbbrev',axis=1)
    #locate the team baseline
    conf_avg=baseline.loc[con,season]
    #sumtract and sume for plus minus
    pm=team-conf_avg
    pm=pm.sum(axis=0)
    pm['ConfAbbrev']=con
    return pm

In [ ]:
team=2022
con='sec'
conf_avg=baseline_ranked.loc[con,season]
conf_avg

DayNum           58.351449
Score            72.521739
FGM              25.793478
FGA              58.586957
FGM3              6.942029
FGA3             21.974638
FTM              13.992754
FTA              19.597826
OR                9.659420
DR               23.550725
Ast              13.518116
TO               12.862319
Stl               8.036232
Blk               4.318841
PF               17.141304
Rank_day         53.789855
RankingDayNum    53.789855
DOK              58.315217
DOL              62.387681
MOR              68.641304
POM              58.721014
SAG              57.253623
WLK              47.268116
Name: (sec, 2022), dtype: float64

In [ ]:
pm=team-conf_avg
pm.sum(axis=0)

45678.985507246376

In [ ]:
pm=games.groupby('TeamID').progress_apply(plus_minus)
pm.head(5)

  0%|          | 0/6892 [00:00<?, ?it/s]

,Ast,Blk,DR,DayNum,FGA,FGA3,FGM,FGM3,FTA,FTM,Loc,OR,PF,Rank_day,Score,Season,Stl,TO,TeamID,ConfAbbrev
TeamID,,,,,,,,,,,,,,,,,,,,
2003_1102,-17.545064,-34.721030,-154.493562,-65.952790,-338.034335,108.802575,-138.403433,44.991416,-146.493562,-129.991416,0,-168.407725,-27.429185,-92.849785,-361.806867,0.0,-7.729614,-62.746781,0,mwc
2003_1103,51.827027,-10.337838,-65.486486,-18.221622,39.272973,-44.410811,67.194595,-21.567568,91.959459,87.400000,0,-36.064865,-19.251351,-15.959459,200.221622,0.0,13.421622,-55.972973,0,mac
2003_1104,-67.837607,-2.410256,12.358974,-70.792023,33.478632,52.159544,-39.444444,1.384615,38.205128,38.678063,0,47.988604,7.940171,-72.370370,-38.826211,0.0,-24.561254,-30.609687,0,sec
2003_1105,36.795775,-20.521127,-14.852113,8.091549,65.894366,47.190141,-0.802817,35.415493,36.739437,46.246479,0,25.450704,19.823944,-8.838028,80.056338,0.0,39.767606,61.126761,0,swac
2003_1106,-40.450704,7.746479,4.774648,-111.901408,-106.267606,-36.718310,-27.633803,-3.014085,-111.126761,-84.042254,0,-6.591549,-36.112676,-156.056338,-142.323944,0.0,16.211268,20.521127,0,swac

In [ ]:
normed_games=games_ranked.groupby('TeamID').progress_apply(normalize_by_conf)
normed_games=normed_games.set_index('TeamID')

  0%|          | 0/6892 [00:00<?, ?it/s]

In [ ]:
#2022 champion Kansas
pm.loc['2022_1242']

Ast            49.124444
Blk            16.857778
DR                 33.48
DayNum         57.151111
FGA            58.164444
FGA3          -11.377778
FGM            85.591111
FGM3           11.293333
FTA            20.746667
FTM            18.493333
Loc                    0
OR                 18.04
PF            -19.017778
Rank_day       77.057778
Score         200.968889
Season               0.0
Stl           -33.328889
TO             -0.048889
TeamID                 0
ConfAbbrev    big_twelve
Name: 2022_1242, dtype: object

In [ ]:
normed_games.to_csv('NCAA_games_normalized_with_rankings.csv')
normed_games.loc['2022_1242']

,Ast,Blk,DOK,DOL,DR,DayNum,FGA,FGA3,FGM,FGM3,...,PF,POM,Rank_day,RankingDayNum,SAG,Score,Season,Stl,TO,WLK
TeamID,,,,,,,,,,,,,,,,,,,,,
2022_1242,0.361899,0.147959,0.0,0.0,0.204819,-0.681037,0.218003,0.349036,0.345234,0.467710,...,-0.452407,0.0,-0.667252,0.0,0.0,0.234876,0.0,-0.007170,-0.448722,0.0
2022_1242,0.003504,-1.000000,0.0,0.0,0.204819,-0.549700,-0.112598,-0.325482,-0.000683,-0.119374,...,-0.026501,0.0,-0.521675,0.0,0.0,-0.003680,0.0,-0.751793,0.181309,0.0
2022_1242,0.576935,-0.426020,0.0,0.0,-0.139415,-0.493412,0.235403,-0.325482,0.498975,-0.119374,...,0.216874,0.0,-0.521675,0.0,0.0,0.347137,0.0,0.241037,-0.291215,0.0
2022_1242,-0.211532,-0.426020,0.0,0.0,-0.440620,-0.530937,0.044003,-0.084582,0.153058,-0.412916,...,0.034343,0.0,-0.521675,0.0,0.0,0.024386,0.0,0.613348,-0.527476,0.0
2022_1242,0.290220,-0.139031,0.0,0.0,0.204819,-0.399600,0.218003,0.300857,0.306799,0.320939,...,0.399405,0.0,-0.376098,0.0,0.0,0.333105,0.0,-0.131274,-0.054953,0.0
2022_1242,0.361899,1.008929,0.0,0.0,0.247849,-0.324550,-0.025597,-0.036403,0.153058,-0.119374,...,-0.209032,0.0,-0.376098,0.0,0.0,0.094549,0.0,0.489244,0.260063,0.0
2022_1242,0.433578,0.721939,0.0,0.0,-0.053356,-0.249500,0.026603,0.300857,0.268364,1.054795,...,-0.026501,0.0,-0.230520,0.0,0.0,0.431333,0.0,-0.255378,-0.133707,0.0
2022_1242,0.003504,0.721939,0.0,0.0,-0.311532,-0.118162,-0.060397,-0.084582,-0.000683,0.027397,...,-0.330719,0.0,-0.084943,0.0,0.0,0.122614,0.0,-0.007170,0.181309,0.0
2022_1242,0.075183,-0.139031,0.0,0.0,0.247849,0.088225,0.131003,-0.132762,0.345234,0.027397,...,0.095187,0.0,0.060634,0.0,0.0,0.234876,0.0,0.241037,0.102555,0.0
2022_1242,0.290220,-0.139031,0.0,0.0,-0.096386,0.144513,0.096203,0.349036,0.076187,0.320939,...,-0.087345,0.0,0.206211,0.0,0.0,0.066484,0.0,-0.007170,-0.291215,0.0
2022_1242,0.075183,0.434949,0.0,0.0,0.376936,0.200801,0.131003,0.108137,0.076187,0.320939,...,-0.209032,0.0,0.206211,0.0,0.0,0.038418,0.0,-0.379482,0.338817,0.0
2022_1242,-0.211532,1.582908,0.0,0.0,-0.139415,0.332138,-0.164798,-0.036403,-0.192860,-0.119374,...,-0.269876,0.0,0.351789,0.0,0.0,-0.129974,0.0,-0.503585,0.260063,0.0
2022_1242,-0.139853,-0.139031,0.0,0.0,-0.268503,0.275851,-0.182198,0.252677,-0.192860,0.467710,...,0.338561,0.0,0.351789,0.0,0.0,-0.059810,0.0,-0.379482,0.338817,0.0
2022_1242,0.648614,1.295918,0.0,0.0,0.290878,0.407188,0.218003,0.011777,0.383669,0.174168,...,0.156030,0.0,0.497366,0.0,0.0,0.192778,0.0,-0.131274,-0.054953,0.0
2022_1242,-0.139853,-0.713010,0.0,0.0,-0.096386,0.463476,-0.008197,-0.180942,0.037752,0.174168,...,-0.087345,0.0,0.497366,0.0,0.0,-0.059810,0.0,-0.379482,-0.054953,0.0
2022_1242,0.003504,-0.139031,0.0,0.0,0.118761,0.538526,0.026603,0.011777,-0.000683,-0.266145,...,-0.148188,0.0,0.642943,0.0,0.0,0.094549,0.0,-0.751793,-0.212461,0.0
2022_1242,0.290220,-0.426020,0.0,0.0,0.376936,0.576051,0.287603,0.108137,0.229928,0.174168,...,0.156030,0.0,0.642943,0.0,0.0,0.319072,0.0,-0.503585,-0.054953,0.0
2022_1242,0.361899,-0.139031,0.0,0.0,0.204819,0.726151,-0.129998,-0.373662,0.076187,-0.266145,...,-0.330719,0.0,0.788520,0.0,0.0,-0.017712,0.0,0.489244,0.732587,0.0
2022_1242,-0.139853,-0.713010,0.0,0.0,-0.139415,0.669863,0.026603,-0.132762,-0.077554,-0.119374,...,-0.209032,0.0,0.788520,0.0,0.0,-0.129974,0.0,-0.503585,-0.212461,0.0
2022_1242,0.290220,0.721939,0.0,0.0,0.462995,0.801201,0.078803,-0.036403,0.229928,-0.266145,...,-0.209032,0.0,0.934097,0.0,0.0,0.164712,0.0,-0.255378,0.102555,0.0
2022_1242,-0.283211,0.434949,0.0,0.0,0.032702,0.838726,-0.164798,-0.373662,0.076187,-0.266145,...,0.277718,0.0,0.934097,0.0,0.0,0.066484,0.0,-0.627689,0.181309,0.0

In [ ]:
seeds=pd.read_csv('https://raw.githubusercontent.com/sebastiancoombs/Kaggle_2022_MM/main/mens-march-mania-2022/MDataFiles_Stage2/MNCAATourneySeeds.csv')

In [ ]:
seeds['TeamID']=seeds.Season.astype(str)+'_'+seeds.TeamID.astype(str)
seeds=seeds.drop('Season',axis=1)
seeds.head(3)

  Seed     TeamID
0  W01  1985_1207
1  W02  1985_1210
2  W03  1985_1228

In [ ]:
pm=pm.drop('TeamID',axis=1).reset_index()
pm.head(5)

,TeamID,Ast,Blk,DR,DayNum,FGA,FGA3,FGM,FGM3,FTA,FTM,Loc,OR,PF,Rank_day,Score,Season,Stl,TO,ConfAbbrev
0,2003_1102,-17.545064,-34.721030,-154.493562,-65.952790,-338.034335,108.802575,-138.403433,44.991416,-146.493562,-129.991416,0,-168.407725,-27.429185,-92.849785,-361.806867,0.0,-7.729614,-62.746781,mwc
1,2003_1103,51.827027,-10.337838,-65.486486,-18.221622,39.272973,-44.410811,67.194595,-21.567568,91.959459,87.400000,0,-36.064865,-19.251351,-15.959459,200.221622,0.0,13.421622,-55.972973,mac
2,2003_1104,-67.837607,-2.410256,12.358974,-70.792023,33.478632,52.159544,-39.444444,1.384615,38.205128,38.678063,0,47.988604,7.940171,-72.370370,-38.826211,0.0,-24.561254,-30.609687,sec
3,2003_1105,36.795775,-20.521127,-14.852113,8.091549,65.894366,47.190141,-0.802817,35.415493,36.739437,46.246479,0,25.450704,19.823944,-8.838028,80.056338,0.0,39.767606,61.126761,swac
4,2003_1106,-40.450704,7.746479,4.774648,-111.901408,-106.267606,-36.718310,-27.633803,-3.014085,-111.126761,-84.042254,0,-6.591549,-36.112676,-156.056338,-142.323944,0.0,16.211268,20.521127,swac

In [ ]:
pm_seed=pd.merge(pm,seeds,left_on='TeamID',right_on='TeamID', how='inner')
pm_seed.to_csv('NCAA_teams_plus_minus.csv')

pm_seed.head(5)

,TeamID,Ast,Blk,DR,DayNum,FGA,FGA3,FGM,FGM3,FTA,...,Loc,OR,PF,Rank_day,Score,Season,Stl,TO,ConfAbbrev,Seed
0,2003_1104,-67.837607,-2.410256,12.358974,-70.792023,33.478632,52.159544,-39.444444,1.384615,38.205128,...,0,47.988604,7.940171,-72.370370,-38.826211,0.0,-24.561254,-30.609687,sec,Y10
1,2003_1112,71.674740,24.117647,97.058824,23.806228,140.041522,52.768166,93.484429,17.664360,96.788927,...,0,61.581315,-45.560554,26.768166,275.923875,0.0,51.269896,-2.705882,pac_ten,Z01
2,2003_1113,13.591696,25.764706,-25.117647,-94.200692,-110.671280,-162.418685,6.501730,-69.740484,135.245675,...,0,20.602076,1.062284,-121.418685,17.564014,0.0,-41.363322,-25.588235,pac_ten,Z10
3,2003_1120,-33.897436,32.846154,-27.615385,-24.991453,-38.487179,-49.829060,7.666667,-20.230769,5.076923,...,0,2.273504,-41.564103,-41.111111,-17.170940,0.0,16.470085,45.632479,sec,W10
4,2003_1122,-48.331933,41.710084,40.827731,118.243697,-156.142857,-23.361345,-77.344538,-10.777311,87.806723,...,0,-19.415966,-23.521008,138.659664,-117.134454,0.0,-3.084034,8.382353,ovc,W13

In [ ]:
tour=pd.read_csv('https://raw.githubusercontent.com/sebastiancoombs/Kaggle_2022_MM/main/mens-march-mania-2022/MDataFiles_Stage2/MNCAATourneyCompactResults.csv')

tour.head(15)

    Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0     1985     136     1116      63     1234      54    N      0
1     1985     136     1120      59     1345      58    N      0
2     1985     136     1207      68     1250      43    N      0
3     1985     136     1229      58     1425      55    N      0
4     1985     136     1242      49     1325      38    N      0
5     1985     136     1246      66     1449      58    N      0
6     1985     136     1256      78     1338      54    N      0
7     1985     136     1260      59     1233      58    N      0
8     1985     136     1314      76     1292      57    N      0
9     1985     136     1323      79     1333      70    N      0
10    1985     136     1326      75     1235      64    N      0
11    1985     136     1328      96     1299      83    N      0
12    1985     136     1374      85     1330      68    N      0
13    1985     136     1385      83     1380      59    N      0
14    1985     136     1396      60     1439      57    N      0

In [ ]:
Tgame=tour.loc[0]
Tgame.Season

1985

In [ ]:
tour_train=pd.DataFrame()
tour_train['Wteam_i']=tour['WTeamID']
tour_train['Lteam_i']=tour['LTeamID']
tour_train['day']=tour.Season.astype(str)+'_'+tour.DayNum.astype(str)
tour_train['Wteam']=tour.Season.astype(str)+'_'+tour.WTeamID.astype(str)
tour_train['Lteam']=tour.Season.astype(str)+'_'+tour.LTeamID.astype(str)
tour_train=pd.merge(tour_train,seeds,left_on='Wteam',right_on='TeamID',how='left')
tour_train.rename(columns={'Seed':'Wseed'},inplace=True)
tour_train=pd.merge(tour_train,seeds,left_on='Lteam',right_on='TeamID',how='left')
tour_train.rename(columns={'Seed':'Lseed'},inplace=True)
tour_train.drop(['TeamID_x','TeamID_y'],axis=1,inplace=True)
tour_train.Wseed=tour_train.Wseed.str.replace("[a-zA-Z]","").astype(int)
tour_train.Lseed=tour_train.Lseed.str.replace("[a-zA-Z]","").astype(int)
tour_train['Win_Loss']=(tour_train['Wseed']>=tour_train['Lseed']).astype(int)

<ipython-input-41-f7de911e673a>:12: FutureWarning: The default value of regex will change from True to False in a future version.
  tour_train.Wseed=tour_train.Wseed.str.replace("[a-zA-Z]","").astype(int)
<ipython-input-41-f7de911e673a>:13: FutureWarning: The default value of regex will change from True to False in a future version.
  tour_train.Lseed=tour_train.Lseed.str.replace("[a-zA-Z]","").astype(int)

In [ ]:
Wtrain=pd.merge(tour_train,pm,left_on='Wteam',right_on='TeamID')
Wtrain=Wtrain.drop('TeamID',axis=1)

In [ ]:
Ltrain=pd.merge(Wtrain,pm,left_on='Lteam',right_on='TeamID')

In [ ]:
data=Ltrain.drop('TeamID',axis=1)
data.head(5)

,Wteam_i,Lteam_i,day,Wteam,Lteam,Wseed,Lseed,Win_Loss,Ast_x,Blk_x,...,FTM_y,Loc_y,OR_y,PF_y,Rank_day_y,Score_y,Season_y,Stl_y,TO_y,ConfAbbrev_y
0,1421,1411,2003_134,2003_1421,2003_1411,16,16,1,38.040909,-0.922727,...,112.669014,0,19.366197,-35.049296,133.725352,123.295775,0.0,-40.345070,-32.084507,swac
1,1112,1436,2003_136,2003_1112,2003_1436,1,16,0,71.674740,24.117647,...,1.616601,0,38.086957,-74.640316,47.553360,12.454545,0.0,-4.802372,-23.561265,aec
2,1112,1211,2003_138,2003_1112,2003_1211,1,9,0,71.674740,24.117647,...,64.517544,0,33.758772,-51.109649,-58.096491,184.464912,0.0,11.267544,-20.118421,wcc
3,1112,1323,2003_143,2003_1112,2003_1323,1,5,0,71.674740,24.117647,...,66.481663,0,-59.095355,-78.799511,-277.127139,202.643032,0.0,-16.393643,-52.779951,big_east
4,1113,1272,2003_136,2003_1113,2003_1272,10,7,1,13.591696,25.764706,...,16.952381,0,44.373434,-4.674185,42.320802,128.746867,0.0,11.145363,-5.854637,cusa

In [ ]:
data=data.drop(data.filter(like='Season').columns,axis=1)
def get_team(day):
  return int(day.split('_')[-1])

def get_season(day):
  return int(day.split('_')[-0])

In [ ]:
data['Season']=data.Lteam.apply(get_season)
data.day=data.day.apply(get_team)
data.Wteam=data.Wteam.apply(get_team)
data.Lteam=data.Lteam.apply(get_team)

data.to_csv('tournament_pm_games.csv',index=False)
data.columns

Index(['Wteam_i', 'Lteam_i', 'day', 'Wteam', 'Lteam', 'Wseed', 'Lseed',
       'Win_Loss', 'Ast_x', 'Blk_x', 'DR_x', 'DayNum_x', 'FGA_x', 'FGA3_x',
       'FGM_x', 'FGM3_x', 'FTA_x', 'FTM_x', 'Loc_x', 'OR_x', 'PF_x',
       'Rank_day_x', 'Score_x', 'Stl_x', 'TO_x', 'ConfAbbrev_x', 'Ast_y',
       'Blk_y', 'DR_y', 'DayNum_y', 'FGA_y', 'FGA3_y', 'FGM_y', 'FGM3_y',
       'FTA_y', 'FTM_y', 'Loc_y', 'OR_y', 'PF_y', 'Rank_day_y', 'Score_y',
       'Stl_y', 'TO_y', 'ConfAbbrev_y', 'Season'],
      dtype='object')

In [ ]:
## create a bunch of images
X_images=[]
Y_dicts=[]
y_teams={}
for i in range(len(data)):
  game=data.loc[i]
  game_dict={}
  ## grab team numbers and seasons
  season=game.Season
  wteam='_'.join([str(season),str(game.Wteam)])
  lteam='_'.join([str(season),str(game.Lteam)])
  game_dict[1]=wteam
  game_dict[0]=lteam
  wteam
  if wteam in normed_games.index:
    Y_dicts.append(game_dict)
    y_teams[i]=game_dict
    ## turn the games into a list of images
    team1=normed_games.loc[wteam].to_numpy()
    team2=normed_games.loc[lteam].to_numpy()
    image,image_for_show=game_image(team1,team2,show=True)
    X_images.append(image)
    if i<2:
      plt.imshow(image_for_show,cmap='coolwarm',)
      plt.colorbar()
      plt.show()
      print(wteam,lteam)

NameError: ignored

# Start building the model pipeline and split the data

In [ ]:
y=data.Win_Loss
x=data.drop(['Win_Loss'],axis=1)
y.head(5)
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [ ]:
cat_features=list (x.filter(like='ConfAbbrev').columns)+ list(x.filter(like='team').columns)+list(x.filter(like='seed').columns)
cat_features.append('day')
cat_features

In [ ]:
ord_features=list (x.filter(like='seed').columns)
ord_features

In [ ]:
num_features=[col for col in x.columns if col not in ord_features+cat_features]

In [ ]:
num_processor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')), 
    ('scaler', StandardScaler())
])
num_processor

In [ ]:
cat_processor = Pipeline(steps=[
    ('cat_imputer', SimpleImputer(strategy='most_frequent')),
    ('cat_encoder',OneHotEncoder(handle_unknown='ignore'))
])
cat_processor

In [ ]:
ord_processor = Pipeline(steps=[
    ('ord_imputer', SimpleImputer(strategy='most_frequent')),
    ('ord_encoder',OrdinalEncoder())
])
ord_processor

In [ ]:
features_processor = ColumnTransformer(transformers = [
    ('num_pipeline', num_processor,num_features),
    ('cat_pipeline', cat_processor,cat_features),
    #('ord_pipeline', ord_processor,ord_features)
],remainder='drop') #drop Name, Sipsp, Parch, Cabin, Ticket
features_processor

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
# classification pipeline
pipe = Pipeline(steps=[
    ('feature_processor', features_processor),
    ('poly_features',PolynomialFeatures()),
    ('classifier',knn)
])
pipe

In [ ]:
# grid search (degree of the poly features, n_neighbors, weights)
param_dic = {'classifier__n_neighbors' : list(range(10,30)),
            'classifier__weights' : ['uniform','distance'],
            'poly_features__degree' : [1,2]
             }
grid = GridSearchCV(pipe,param_dic,cv=5,scoring='accuracy',n_jobs=-1,verbose=1)

In [ ]:
grid.fit(xtrain,ytrain)

In [ ]:
pd.DataFrame(grid.cv_results_)

In [ ]:
grid.best_params_

In [ ]:
grid.best_score_

In [ ]:
best_clf=grid.best_estimator_

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
ypred=best_clf.predict(xtest)
accuracy_score(ypred,ytest)

In [ ]:
accuracy_score(ypred,ytest)

In [ ]:
import xgboost as xgb
xgb.XGBClassifier()

In [ ]:
forest_clf= xgb.XGBClassifier()

In [ ]:
pipe2 = Pipeline(steps=[
    ('feature_processor', features_processor),
    ('clf',forest_clf)
])
pipe2

In [ ]:
# grid search (degree of the poly features, n_neighbors, weights)
param_dic2 ={'clf__max_depth':[2,5,10,20],
             'clf__learning_rate':[.01,.05,.1,.2,.3,.4,.5],
              'clf__gamma':[0,.1,.5,.6,.8],
              #'clf__n_estimators':[100,200,400,800],
              #'clf__min_child_weight':[1,2,3,4,5,6,8],
            #  'clf__subsample':[.5,.6,.7,.8,.9,1],
            #  'clf__colsample_bytree':[.5,.7,.8,.9,1],
             }
grid = GridSearchCV(pipe2,param_dic2,cv=5,scoring='accuracy',n_jobs=-1,verbose=1)

In [ ]:
grid.fit(xtrain,ytrain)

In [ ]:
grid.best_params_

In [ ]:
grid.best_score_

In [ ]:
best_clf=grid.best_estimator_

Submissions are scored on the log loss:

$$
LogLoss=\frac{-1}{n}\sum_{𝑖=1}^{𝑛}[𝑦𝑖log(𝑦̂ 𝑖)+(1−𝑦𝑖)log(1−𝑦̂ 𝑖)],
$$
where

𝑛 is the number of games played
𝑦̂ 𝑖 is the predicted probability of team 1 beating team 2
𝑦𝑖 is 1 if team 1 wins, 0 if team 2 wins
𝑙𝑜𝑔 is the natural logarithm

The use of the logarithm provides extreme punishments for being both confident and wrong. In the worst possible case, a prediction that something is true when it is actually false will add an infinite amount to your error score. In order to prevent this, predictions are bounded away from the extremes by a small value.

In [ ]:
ypred=best_clf.predict(xtest)
yproba=best_clf.predict_proba(xtest)
yproba=np.array(yproba)
accuracy_score(ypred,ytest)

In [ ]:
def logloss(y,yhat):
  n=len(y)
  z=y*np.log(yhat)+(1-y)*np.log(1-yhat)
  loss=(-1/n)*np.sum(z)
  return loss

In [ ]:
logloss(ytest,yproba[:,0])

Submission File
The file you submit will depend on whether the competition is in stage 1--historical model building--or stage 2--the 2022 tournament. Sample submission files will be provided for both stages. The format is a list of every possible matchup between the tournament teams. Since team1 vs. team2 is the same as team2 vs. team1, we only include the game pairs where team1 has the lower team id. For example, in a tournament of 68 teams, you will predict (68∗67)/2=2,278 matchups.

Each game has a unique id created by concatenating the season in which the game was played, the team1 id, and the team2 id. For example, "2016_1107_1110" indicates team 1107 potentially played team 1110 in the year 2016. You must predict the probability that the team with the lower id beats the team with the higher id.

The resulting submission format looks like the following, where "pred" represents the predicted probability that the first team will win:

ID,Pred\
2016_1107_1110,0.5\
2016_1107_1112,0.5\
2016_1107_1113,0.5

## im gonna try this with a CNN neural network

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.models                 import Sequential
from keras                        import layers
from keras.layers.core            import Dense,Activation,Dropout
from scikeras.wrappers            import KerasClassifier
from keras.utils                  import np_utils

In [ ]:
y=data.Win_Loss

In [ ]:
y.unique()

In [ ]:
y=data.Win_Loss
y=y.to_numpy()
xtrain,xtest,ytrain,ytest=train_test_split(X_images,y)
X_images[0].shape
len(X_images),len(y)

In [ ]:
#pip install scikeras[tensorflow]

In [ ]:
# Convolutional layer and maxpool layer 1
model = Sequential()
model.add(keras.layers.Conv2D(16,(3,3),activation='relu',input_shape=(32,32,2)))
model.add(keras.layers.MaxPool2D(2,2))

# Convolutional layer and maxpool layer 2
model.add(keras.layers.Conv2D(32,(3,3),activation='relu'))
model.add(keras.layers.MaxPool2D(2,2))

# Convolutional layer and maxpool layer 3
model.add(keras.layers.Conv2D(64,(3,3),activation='relu'))
model.add(keras.layers.MaxPool2D(2,2))

# Convolutional layer and maxpool layer 4
# model.add(keras.layers.Conv2D(64,(3,3),activation='relu'))
# model.add(keras.layers.MaxPool2D(2,2))

# This layer flattens the resulting image array to 1D array
model.add(keras.layers.Flatten())

# Hidden layer with 512 neurons and Rectified Linear Unit activation function 
model.add(keras.layers.Dense(512,activation='relu'))

# Output layer with single neuron which gives 0 for Cat or 1 for Dog 
#Here we use sigmoid activation function which makes our model output to lie between 0 and 1
model.add(keras.layers.Dense(1,activation='sigmoid'))

In [ ]:
  # ## im gonna try this with a CNN neural network
# def create_model(activation='relu', dropout=0.2):
#       model = Sequential()

#       ## layer 1
#       model.add(layers.Conv2D(16, (3, 3), activation='softmax', input_shape=(32, 32, 2)))
#       model.add(layers.MaxPooling2D((2, 2)))
#       model.add(layers.Dropout(.2))
#       ## layer 2
#       model.add(layers.Conv2D(32, (3, 3), activation='softmax', input_shape=(32, 32, 2)))
#       model.add(layers.MaxPooling2D((2, 2)))
#       model.add(layers.Dropout(.2))

#       model.add(layers.Dense(32, activation='relu'))
# # Only 1 output neuron. It will contain a value from 0-1 where 0 for 1 class ('dandelions') and 1 for the other ('grass')
#       model.add (layers.Dense(1, activation='sigmoid'))

#       model.compile(optimizer='adam',loss=tf.keras.losses.binary_crossentropy,metrics=['accuracy'])
#       model.summary()
#       return model

# model=create_model()

In [ ]:
model.fit(xtrain,ytrain)

In [ ]:
test_loss, test_acc = cnn_pipe.evaluate(xtest, ytest, verbose=2)
print(test_loss,test_acc)